apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: 35.240.181.15-xip-io-tls
spec: 
  secretName: 35.240.181.15-xip-io
  issuerRef:
    name: letsencrypt-prod
    kind: CLusterIssuer
  commonName: 35.240.181.15.xip.io
  dnsNames:
    - 35.240.181.15.xip.io
    - www.35.240.181.15.xip.io
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - 35.240.181.15.xip.io
          - www.35.240.181.15.xip.io